### ISSUE TITLE
[평가] 1차 최종결과 선택

### ISSUE THREAD

**Issue by devrokket** [PickSa/picksa-server#24]
## 🦁 Describe

- 파트장이 지원자의 1차 최종 결과를 선택한다. 

## ✅ Tasks

- [ ] Manager 중 `PART_LEADER` Position인지 아닌지 판단. (인증 서버 연동 전)
- [ ] pass가 True일 때 score 누적
- [ ] 지원자의 Result를 미정, 합격, 불합격 셋 중 하나로 결정
